[package]
name = "yaqlite"
version = "0.0.1"
edition = "2021"

[dependencies]
rusqlite = { version = "0.27.0", features = ["modern_sqlite"] }
thiserror = "1.0.30"
yaml-rust = "0.4.5"

[dependencies.clap]
version = "3.1.6"
default-features = false
features = ["std", "derive", "suggestions"]
